title: 'Page Example'

table: 'users'

gallery: 0

register:
    labels: ['Name', 'Email', 'Password']
    fields: ['name', 'email', 'password']
    type: ['input', 'email', 'password']
    plus: []

list:
    labels: ['Name', 'Email', 'Password']
    fields: ['name', 'email', 'password']
    type: ['input', 'email', 'password']
    plus: []
