title: 'Page Example: Users'

table: 'users'

gallery: 0

register:
  - type: 'input'
    label: 'Name'
    field: 'name'

  - type: 'email'
    label: 'Email'
    field: 'email'

  - type: 'password'
    label: 'Password'
    field: 'password'

  - type: 'dolar'
    label: 'Dolar'
    field: 'dolar'

  - type: 'image'
    label: 'Image'
    field: 'image'


list:
  - type: 'input'
    label: 'Name'
    field: 'name'

  - type: 'email'
    label: 'Email'
    field: 'email'

  - type: 'password'
    label: 'Password'
    field: 'password'

  - type: 'dolar'
    label: 'Dolar'
    field: 'dolar'

  - type: 'image'
    label: 'Image'
    field: 'image'
