commonsHome:
    path:     /
    defaults: {
        _controller: '\App\Controllers\Commons::home'
      }
    options:
        utf8: true

commonsSetLocale:
    path:     /lang/{lang}
    defaults: { _controller: '\App\Controllers\Commons::setLocale' }
    options:
        utf8: true

commonsGeneratePdf:
    path:     /pdf
    defaults: { _controller: '\App\Controllers\Commons::generatePDF' }
    options:
        utf8: true

commonsGenerateCsv:
    path:     /csv
    defaults: { _controller: '\App\Controllers\Commons::generateCSV' }
    options:
        utf8: true

commonsSocket:
    path:     /socket
    defaults: { _controller: '\App\Controllers\Commons::socket' }
    options:
        utf8: true

commonsScriptKey:
    path:     /script-key
    defaults: { _controller: '\App\Controllers\Commons::scriptKey' }
    options:
        utf8: true

commonsSendMail:
    path:     /mail/{email}
    defaults: { _controller: '\App\Controllers\Commons::sendMail' }
    options:
        utf8: true

commonsList:
    path:     /users/list
    defaults: {
        _controller: '\App\Controllers\Commons::list',
      }
    methods: [GET]
    options:
        utf8: true

commonsImport:
    path:     /users/import
    defaults: { _controller: '\App\Controllers\Commons::import' }
    methods: [POST]
    options:
        utf8: true

usersSave:
    path:     /users
    defaults: {
        _controller: '\App\Controllers\Users::save',
        _middlewares: [
          'Framework\Middlewares\AuthenticationJWTMiddleware',
        ]
      }
    methods: [POST]
    options:
        utf8: true

usersList:
    path:     /users
    defaults: {
        _controller: '\App\Controllers\Users::list',
        _middlewares: [
          'Framework\Middlewares\AuthenticationJWTMiddleware',
        ]
      }
    methods: [GET]
    options:
        utf8: true

usersUpdate:
    path:     /users/{id}
    defaults: {
        _controller: '\App\Controllers\Users::update',
        _middlewares: [
          'Framework\Middlewares\AuthenticationJWTMiddleware',
        ]
      }
    methods: [PUT]
    options:
        utf8: true

usersDelete:
    path:     /users/{id}
    methods: [DELETE]
    defaults: {
        _controller: '\App\Controllers\Users::delete',
        _middlewares: [
          'Framework\Middlewares\AuthenticationJWTMiddleware',
        ]
      }
    options:
        utf8: true

usersView:
    path:     /users/{id}
    methods: [GET]
    defaults: {
        _controller: '\App\Controllers\Users::view',
        _middlewares: [
          'Framework\Middlewares\AuthenticationJWTMiddleware',
        ]
      }
    options:
        utf8: true
